# Generated by Django 4.2 on 2025-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patient_current_weight_patient_has_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('GENERAL', 'General Consultation'), ('FOLLOWUP', 'Follow-up Visit'), ('SPECIALIST', 'Specialist Consultation')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
